const FETCH_CATS_BEGIN = 'FETCH_CATS_BEGIN';
const FETCH_CATS_SUCCESS = 'FETCH_CATS_SUCCESS';
const FETCH_CATS_FAILURE = 'FETCH_CATS_FAILURE';

const FETCH_HOBBIES_BEGIN = 'FETCH_HOBBIES_BEGIN';
const FETCH_HOBBIES_SUCCESS = 'FETCH_HOBBIES_SUCCESS';
const FETCH_HOBBIES_FAILURE = 'FETCH_HOBBIES_FAILURE';

const UPDATE_CAT_BEGIN = 'UPDATE_CAT_BEGIN';
const UPDATE_CAT_SUCCESS = 'UPDATE_CAT_SUCCESS';
const UPDATE_CAT_FAILURE = 'UPDATE_CAT_FAILURE';

export {
  FETCH_CATS_BEGIN,
  FETCH_CATS_SUCCESS,
  FETCH_CATS_FAILURE,
  FETCH_HOBBIES_BEGIN,
  FETCH_HOBBIES_SUCCESS,
  FETCH_HOBBIES_FAILURE,
  UPDATE_CAT_BEGIN,
  UPDATE_CAT_SUCCESS,
  UPDATE_CAT_FAILURE
}
