const FETCH_PERSONS_BEGIN = 'FETCH_PERSONS_BEGIN';
const FETCH_PERSONS_SUCCESS = 'FETCH_PERSONS_SUCCESS';
const FETCH_PERSONS_FAILURE = 'FETCH_PERSONS_FAILURE';

export {
  FETCH_PERSONS_BEGIN,
  FETCH_PERSONS_SUCCESS,
  FETCH_PERSONS_FAILURE
}
