const FETCH_PERSONS_BEGIN = 'FETCH_PERSONS_BEGIN';
const FETCH_PERSONS_SUCCESS = 'FETCH_PERSONS_SUCCESS';
const FETCH_PERSONS_FAILURE = 'FETCH_PERSONS_FAILURE';

const FETCH_HOBBIES_BEGIN = 'FETCH_HOBBIES_BEGIN';
const FETCH_HOBBIES_SUCCESS = 'FETCH_HOBBIES_SUCCESS';
const FETCH_HOBBIES_FAILURE = 'FETCH_HOBBIES_FAILURE';

export {
  FETCH_PERSONS_BEGIN,
  FETCH_PERSONS_SUCCESS,
  FETCH_PERSONS_FAILURE,
  FETCH_HOBBIES_BEGIN,
  FETCH_HOBBIES_SUCCESS,
  FETCH_HOBBIES_FAILURE
}
